# Generated by Django 4.1.7 on 2023-04-15 13:01

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nazwa kursu")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="opis kursu"),
                ),
                (
                    "trainees",
                    models.ManyToManyField(
                        related_name="trainees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uczestnicy kursu",
                    ),
                ),
            ],
        ),
    ]
