# Generated by Django 4.1.7 on 2023-05-27 09:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[("pdf", "Pdf"), ("video", "Video")], max_length=5
                    ),
                ),
                ("youtube_video_url", models.URLField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="pdf")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
    ]
