# Generated by Django 4.1.7 on 2023-05-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="pdf_file",
            new_name="pdf_url",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="youtube_video_url",
            new_name="video_url",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_type",
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="pdf_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="pdf_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="course.course",
            ),
        ),
    ]
