# Generated by Django 4.1.7 on 2023-06-15 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0003_rename_pdf_file_lesson_pdf_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_feedback", models.TextField()),
                ("course_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SiteFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_feedback", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, verbose_name="course description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100, verbose_name="course name"),
        ),
        migrations.AlterField(
            model_name="course",
            name="trainees",
            field=models.ManyToManyField(
                related_name="trainees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="course participants",
            ),
        ),
    ]
